package com.oplus.aiunit.core.protocol.common;

import com.coui.appcompat.hapticfeedback.COUIHapticFeedbackConstants;
import com.coui.appcompat.vibrateutil.VibrateUtils;
import com.oplus.media.OplusRecorder;

/* loaded from: classes3.dex */
public enum ErrorCode {
    UNKNOWN(-1),
    kErrorNone(0),
    kErrorOperationNoPerm(1),
    kErrorNoSuchFileOrDirectory(2),
    kErrorIOError(5),
    kErrorParamLengthMismatch(7),
    kErrorNoMemory(12),
    kErrorPermissionDenied(13),
    kErrorBusy(16),
    kErrorFileExists(17),
    kErrorNotADirectory(20),
    kErrorIsADirectory(21),
    kErrorInvalidParam(22),
    kErrorTooManyFiles(24),
    kErrorFileTooBig(27),
    kErrorReadOnlyFile(30),
    kErrorOutOfMathDomain(33),
    kErrorOutOfMathRange(34),
    kErrorFileNameTooLong(36),
    kErrorMethodNotImplement(38),
    kErrorDirectoryNotEmpty(39),
    kErrorNoDataAvailable(61),
    kErrorTimeOut(62),
    kErrorOutOfResources(63),
    kErrorCommunication(70),
    kErrorProtocol(71),
    kErrorCannotExecASharedLib(83),
    kErrorNoBufferSpace(105),
    kErrorRemoteDead(106),
    KErrorNetworkUnavailable(107),
    kErrorRequestLimit(108),
    kErrorEnvFailed(200),
    kErrorGetRuntime(201),
    kErrorInterrupt(202),
    kErrorNewTask(203),
    kErrorScheduleApi(204),
    kErrorTaskPending(205),
    kErrorRepeatedTask(206),
    kErrorInvalidTask(207),
    kErrorRepeatedLlmTask(208),
    kErrorEnvBattery(211),
    kErrorEnvMemory(212),
    kErrorEnvGaming(213),
    kErrorEnvNetwork(214),
    kErrorEnvPower(215),
    kErrorEnvTemperature(216),
    kErrorEngineNotFound(300),
    kErrorConfigFileInvalid(COUIHapticFeedbackConstants.KEYBOARD_TOUCH_FEEDBACK),
    kErrorConfigInvalid(COUIHapticFeedbackConstants.GRANULAR_SHORT_VIBRATE),
    kErrorModelFileNotFound(COUIHapticFeedbackConstants.SHORT_VIBRATE),
    kErrorModelFileInvalid(304),
    kErrorInvalidServiceState(COUIHapticFeedbackConstants.STEPPING_SHORT_VIBRATE),
    kErrorCodeExpiration(COUIHapticFeedbackConstants.EDGE_SHORT_VIBRATE),
    kErrorNotReady(COUIHapticFeedbackConstants.EDGE_LIST_VIBRATE),
    kErrorVersionMismatch(COUIHapticFeedbackConstants.GRANULAR_SHORT_VIBRATE_SYNC),
    kErrorServiceVersionOutOfDate(309),
    kErrorClientVersionOutOfDate(310),
    kErrorNoNeed(311),
    kErrorPluginVersion(312),
    kErrorPluginManifest(313),
    kErrorCheckSumInvalid(314),
    kErrorOaaNotFound(350),
    kErrorNotInit(VibrateUtils.STRENGTH_OFFSET),
    kErrorPluginNotFound(401),
    kErrorPluginNoVersion(402),
    kErrorPluginNoPluginImplementation(403),
    kErrorPluginClassNotInstantiation(404),
    kErrorAssetsFilesIllegal(405),
    kErrorAssetsCopyFailed(406),
    kErrorPluginLoadFailed(407),
    kErrorNoClassLoader(408),
    kErrorNoPluginContext(409),
    kErrorPluginPathNotExists(410),
    KErrorClassNotFound(411),
    kErrorMDPError(500),
    kErrorSynchronizeFailed(501),
    kErrorPluginNotUsable(502),
    kErrorFileCRCError(503),
    kErrorNoUpdate(504),
    kErrorNoRemoteConfig(505),
    kErrorConfigNotIllegalNoDownloadParam(506),
    kErrorDownloadError(507),
    kErrorSyncFailed(508),
    kErrorDetectorHasEmptyEngine(509),
    kErrorDetectorUpdateSubEngineFailed(510),
    kErrorUnknownConfig(511),
    kErrorDownloadNotAllowed(512),
    kErrorUpdateInMainThread(513),
    kErrorUpdateButNoListener(514),
    kErrorUpdateWaitFailed(515),
    kErrorRouteDisabled(600),
    kErrorRouteNotFound(601),
    kErrorApiLevelNotSupported(OplusRecorder.NAMR_BYTES_P_SEC),
    kErrorSdkVersionNotSupported(701),
    kErrorAIUnitVersionNotSupported(702),
    kErrorOSVersionNotSupported(703),
    kErrorDeviceNotSupported(704),
    kErrorUnitNotFound(800),
    kErrorDetectorNotFound(OplusRecorder.MEDIA_RECORDER_INFO_MAX_FILESIZE_REACHED),
    kErrorAuthorizeFail(802),
    kErrorRouterFail(803),
    kErrorAttachFail(804),
    kErrorProcessFail(805),
    kErrorLowMemory(900),
    kErrorLowBattery(901),
    kErrorLowPowerSaveModel(902),
    kErrorOverload(903),
    kErrorHighTemperature(904),
    kErrorUserForceLocal(905),
    kErrorPrivacyReject(906),
    kErrorUrlEmpty(907),
    kErrorNoInternet(950),
    kErrorNoDownload(951),
    kErrorSwitchClose(952),
    kErrorNoApply(953),
    kErrorApplying(954),
    kErrorApplyFail(955),
    kErrorNoAccount(956),
    kErrorOffline(957),
    kErrorDetectNotInit(958),
    kErrorDetectNotAvailable(959),
    kErrorInProcessing(960),
    kErrorDetectNotInstalled(961),
    kErrorConcurrencyError(962);

    private int value;

    ErrorCode(int i10) {
        this.value = i10;
    }

    public int a() {
        return this.value;
    }
}
